version: "3"

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=${MY_APP_DATABASE_USER}
      - POSTGRES_PASSWORD=${MY_APP_DATABASE_PASSWORD}
      - POSTGRES_DB=${MY_APP_DATABASE_NAME}
  rails:
    build: .
    ports:
      - "3000:${PORT:-3000}"
    environment:
      - DATABASE_URL=postgres://${MY_APP_DATABASE_USER}:${MY_APP_DATABASE_PASSWORD}@db:5432/${MY_APP_DATABASE_NAME}
    depends_on:
      - db
