apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
data:
  POSTGRES_USER: "dbuser"
  POSTGRES_PASSWORD: "dbpasswd"
  POSTGRES_DB: "my_app_development"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DATABASE_URL: postgres://dbuser:dbpasswd@db:5432/my_app_development
